In [17]:
#Numpy array is a fast, flexible container for large data sets in Python.

import numpy as np
my_array = np.array([1, 2, 3])
my_array

#Multi-dimentional array
my_ndarray = np.array([[3,4,5],[6,7,8]])
print("my_ndarray = ",my_ndarray)
print("np.zeros = ",np.zeros((3,6)))

my_ndarray =  [[3 4 5]
 [6 7 8]]
np.zeros =  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
#Basic indexing and slicing
my_ndarray = np.array([[3,4,5],[6,7,8],[7,2,8],[6,6,6]])


print(my_ndarray[0][1])
print(my_ndarray[0,1])
print(my_ndarray[:1])
print(my_ndarray[:2,1:])
print(my_ndarray[:,:1])

4
4
[[3 4 5]]
[[4 5]
 [7 8]]
[[3]
 [6]
 [7]
 [6]]


In [19]:
# Boolean Indexing

names = np.array(['one','two','two','six','five','seven','two','one'])
data = np.random.randn(8,5)
print(names)
print(data)
print('\n')
print(names == 'one')
print(data[names == 'one'])
print('\n')
print(data[names == 'one', 3])


['one' 'two' 'two' 'six' 'five' 'seven' 'two' 'one']
[[-1.42541363 -0.74992025  2.000302    0.66950898  0.86506428]
 [ 1.32687567  0.32203969  1.08593956  1.65003947  0.63365086]
 [ 0.27654844  0.12270779 -1.91979805  0.34162652  1.36132855]
 [ 0.80263463 -0.69115579  1.90252134 -1.37954677  1.81653947]
 [ 0.07264898  0.82144606 -0.50386146 -0.45648058  1.26423587]
 [-0.76346101 -0.01893189  1.24192573  0.75978429  0.02701879]
 [ 1.26371508  0.15091135 -0.23897708  0.53073569 -0.07513877]
 [-0.44930281  1.3693586  -0.50366086  0.13172849 -0.67930703]]


[ True False False False False False False  True]
[[-1.42541363 -0.74992025  2.000302    0.66950898  0.86506428]
 [-0.44930281  1.3693586  -0.50366086  0.13172849 -0.67930703]]


[0.66950898 0.13172849]


In [20]:
# Fancy Indexing
my_array_2 = np.empty((7,5))
for i in range(7):
    my_array_2[i]=i
         
print(my_array_2)
print('\n')

# Select a subset of the rows in a particular order
print(my_array_2[[5,6,2,3]])
print('\n')
print(my_array_2[[-5,-6,-2,-3]])
print('\n')

# Reshape
my_array_3 = np.arange(16).reshape((2,8))
print(my_array_3)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]


[[5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5.]
 [4. 4. 4. 4. 4.]]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [37]:
# Inner matrix product
my_array_4 = np.random.randn(6,3)
print(my_array_4)
print(np.dot(my_array_4.T,my_array_4))
print('\n')

# Transposing
my_array_5 = np.arange(16).reshape(((2,2,4)))
print(my_array_5)
my_array_5.transpose((1,0,2))

[[ 0.18923233 -1.02335551  0.6577996 ]
 [-0.39907635  0.34950608 -1.13483097]
 [-0.99440155 -0.99325095  0.86102299]
 [-0.8939177  -1.03570296  0.06107991]
 [-0.55785332 -1.53601465 -1.22538365]
 [ 0.28379818  0.60924201 -1.11177591]]
[[ 2.37473585  2.61016459  0.03462251]
 [ 2.61016459  5.9591559  -0.78339906]
 [ 0.03462251 -0.78339906  5.20324373]]


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [41]:
# Conditional logic as array operations
my_array_6 = np.random.randn(4,4)
print(my_array_6)
np.where(my_array_6>0,2,my_array_6)

[[ 1.28844554e+00  6.70547126e-01 -7.78570711e-01 -7.41115279e-02]
 [-9.05586246e-01  1.37519502e-01  9.82722213e-04  8.84700763e-02]
 [ 2.44903195e-02  3.03942302e-01  1.02565987e+00  7.90524282e-01]
 [ 3.14764249e-02 -1.53772892e-01 -6.98316066e-01  9.52910340e-01]]


array([[ 2.        ,  2.        , -0.77857071, -0.07411153],
       [-0.90558625,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.15377289, -0.69831607,  2.        ]])

In [50]:
# Mathematical and statistical methods
my_array_7 = np.random.rand(5,5)
for i in range(5):
    my_array_7[i]=i
print(my_array_7)
print('\n')
print(my_array_7.mean())

my_array_7.cumsum(0)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


2.0


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10.]])

In [67]:
# Linear algebra
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6],[11,21],[8,9]])
print (x, '\n\n', y)
print('\n')
print(x.dot(y))

from numpy.linalg import inv,qr
math = x.T.dot(x)
print('\n')
print(math)
print('\n')
r = qr(math)
print(r)

[[1 2 3]
 [4 5 6]] 

 [[ 5  6]
 [11 21]
 [ 8  9]]


[[ 51  75]
 [123 183]]


[[17 22 27]
 [22 29 36]
 [27 36 45]]


(array([[-0.43864578,  0.8005768 ,  0.40824829],
       [-0.56765924,  0.10533905, -0.81649658],
       [-0.69667271, -0.5898987 ,  0.40824829]]), array([[-3.87556448e+01, -5.11925427e+01, -6.36294407e+01],
       [ 0.00000000e+00, -5.68830885e-01, -1.13766177e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.55431223e-15]]))
