In [84]:
#---------------------------------list---------------------------------------#

#list is a collection which is ordered and changeable. Allows duplicate members. Content can be modified.
#Two ways to define a list
my_list = ['Niu','Gu','Shi']

food = ['apples','beef','potatos','pasta']
my_list_2 = list (food)

# Combining lists
my_list_combined = my_list + my_list_2
my_list_combined.extend(['a','b','c'])

my_list_combined

['Niu', 'Gu', 'Shi', 'apples', 'beef', 'potatos', 'pasta', 'a', 'b', 'c']

In [85]:
# Adding/removing elements
my_list.append('Santa')

# Insert an element at a specific location
my_list.insert(1,'(1,2)')

print (my_list)

['Niu', '(1,2)', 'Gu', 'Shi', 'Santa']


In [86]:
# Remove an element at a particular index
my_list.pop(1)
my_list

# Element can also be removed by value
my_list.remove('Santa')
my_list

['Niu', 'Gu', 'Shi']

In [87]:
# Check if a list contains a value
'Gu' in my_list

True

In [88]:
# Sort a list 
list_a = [1,5,7,3,5,9,7,33,4,77,8,5,701,109]
list_a.sort()
list_a

# Sort strings by lengths
my_list.sort(key=len)
my_list


['Gu', 'Niu', 'Shi']

In [89]:
# Binary search & Maintain a sorted list
import bisect as bi

# Find the location to be inserted
bi.bisect(list_a,55)

# Find the location and insert a new element in a sorted list
bi.insort(list_a,888)

list_a

[1, 3, 4, 5, 5, 5, 7, 7, 8, 9, 33, 77, 109, 701, 888]

In [90]:
# Slicing 
print(my_list[1:2])
print(my_list[:1])
print(my_list[2:])
print(my_list[-2])
print(my_list[-2:])
print(my_list[::2])
print(my_list[::-2])
print(my_list[-2::])
print(my_list[-2:-1])


['Niu']
['Gu']
['Shi']
Niu
['Niu', 'Shi']
['Gu', 'Shi']
['Shi', 'Gu']
['Niu', 'Shi']
['Niu']


In [91]:
#---------------------------------tuple---------------------------------------#

# A tuple is a one-dimensional, fixed-length, immutable sequence of Python Objects

my_tup = 4,5,6
print(my_tup)

# Element can be accessed with []
print(my_tup[2])

# Unpacking tuples
a,b,c = my_tup
print(b)

my_tup2 = 7,8,(9,10)
a,b,(c,d) = my_tup2

(4, 5, 6)
6
5


In [92]:
# Any sequence can be converted to a tuple

print(tuple(['can','I','be','a','tuple','?']))

tuple_string = tuple('string')

('can', 'I', 'be', 'a', 'tuple', '?')


In [93]:
# tuple method

my_tup3 = ('a','e','f','c','g','b','c','d','e','a','a','a')
my_tup3.count('a')

4

In [94]:
#---------------------------------set---------------------------------------#

# A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets.
my_set = {'apples','bananas','carrots'}
print (my_set)

# Check if a set is a subset of another set
my_set_2 = {'apples'}

{'carrots', 'apples', 'bananas'}


In [95]:
# Mathematical set operations

set_a = {1,6,8,9,3}
set_b = {0,6,8,10,29,46,74,66}
print(set_a | set_b) #union
print(set_a ^ set_b)#symmetric difference
print(set_a & set_b) # and
print(set_a - set_b) # difference

{0, 1, 66, 3, 6, 8, 9, 10, 74, 46, 29}
{0, 1, 66, 3, 9, 10, 74, 29, 46}
{8, 6}
{1, 3, 9}


In [96]:
#---------------------------------dictionary---------------------------------------#

# A dictionary is a collection which is unordered, changeable and indexed. 
# In Python dictionaries are written with curly brackets, and they have keys and values.

thisdict = {
  "brand": "Nike",
  "model": "classic",
  "price": 198
}

print(thisdict.keys())
print(thisdict.values())

print(thisdict['model'])

# Check if a dict contains a key
print("brand" in thisdict)

# One dict can be merged into anothor dict
thisdict.update({'color': 'blk'})

dict_keys(['brand', 'model', 'price'])
dict_values(['Nike', 'classic', 198])
classic
True


In [97]:
 # Categorizing a list of color by it's first letter with a 'for loop'

colors = ['black','red','yellow','blue','grey','orange','green']
by_letter = {}
for color in colors:
    letter = color[0]
    if letter not in by_letter:
        by_letter[letter] = [color]
    else:
        by_letter[letter].append(color)
            
by_letter

{'b': ['black', 'blue'],
 'g': ['grey', 'green'],
 'o': ['orange'],
 'r': ['red'],
 'y': ['yellow']}

In [98]:
# List, set and dict comprehension allows you to form a new list by filtering the elements

#[expr for val in collection if condition]

the_city = ['yellow','taxi','New York']
print( [x.upper() for x in the_city if len(x)>7] )


lengths = {len(x) for x in the_city}
print(lengths)

mapping = {k : index for index, k in enumerate(the_city)}
print(mapping)

['NEW YORK']
{8, 4, 6}
{'yellow': 0, 'taxi': 1, 'New York': 2}


In [99]:
#Numpy array is a fast, flexible container for large data sets in Python.

import numpy as np
my_array = np.array([1, 2, 3])
my_array

#Multi-dimentional array
my_ndarray = np.array([[3,4,5],[6,7,8]])
print("my_ndarray = ",my_ndarray)
print("np.zeros = ",np.zeros((3,6)))

my_ndarray =  [[3 4 5]
 [6 7 8]]
np.zeros =  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [100]:
#Basic indexing and slicing
my_ndarray = np.array([[3,4,5],[6,7,8],[7,2,8],[6,6,6]])


print(my_ndarray[0][1])
print(my_ndarray[0,1])
print(my_ndarray[:1])
print(my_ndarray[:2,1:])
print(my_ndarray[:,:1])

4
4
[[3 4 5]]
[[4 5]
 [7 8]]
[[3]
 [6]
 [7]
 [6]]


In [101]:
# Boolean Indexing

names = np.array(['one','two','two','six','five','seven','two','one'])
data = np.random.randn(8,5)
print(names)
print(data)
print('\n')
print(names == 'one')
print(data[names == 'one'])
print('\n')
print(data[names == 'one', 3])


['one' 'two' 'two' 'six' 'five' 'seven' 'two' 'one']
[[-0.24774455  0.73454184 -0.37422328  0.37411579  0.97952412]
 [-1.37891765 -1.34310692 -1.86722295 -1.02308476 -0.87667148]
 [-1.09854278  0.44948022 -0.93661421 -0.61809116 -1.4396636 ]
 [-2.6021431   0.92407431  1.46613664 -1.5271968  -1.80732396]
 [-1.00857775 -0.18827108  1.06437784 -2.49040597 -0.19208846]
 [-0.38964058 -1.20151505 -0.23066715  0.59582713  0.54854368]
 [ 1.31347499 -0.08189861 -0.32163023 -1.12927029  1.395261  ]
 [-1.45142683  0.05354772  0.34478953  0.31702648 -0.35093417]]


[ True False False False False False False  True]
[[-0.24774455  0.73454184 -0.37422328  0.37411579  0.97952412]
 [-1.45142683  0.05354772  0.34478953  0.31702648 -0.35093417]]


[0.37411579 0.31702648]


In [102]:
# Fancy Indexing
my_array_2 = np.empty((7,5))
for i in range(7):
    my_array_2[i]=i
         
print(my_array_2)
print('\n')

# Select a subset of the rows in a particular order
print(my_array_2[[5,6,2,3]])
print('\n')
print(my_array_2[[-5,-6,-2,-3]])
print('\n')

# Reshape
my_array_3 = np.arange(16).reshape((2,8))
print(my_array_3)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]


[[5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5.]
 [4. 4. 4. 4. 4.]]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [103]:
# Inner matrix product
my_array_4 = np.random.randn(6,3)
print(my_array_4)
print(np.dot(my_array_4.T,my_array_4))
print('\n')

# Transposing
my_array_5 = np.arange(16).reshape(((2,2,4)))
print(my_array_5)
my_array_5.transpose((1,0,2))

[[-0.70440149 -0.84866631  0.43592109]
 [-0.76317825  1.84023575 -0.38184291]
 [-0.33096344 -0.69033619 -0.76337397]
 [-1.7292487   1.55936653  0.52333289]
 [-0.62440123  0.36471972  0.66486091]
 [-0.61549923 -1.94970015 -1.20438626]]
[[ 4.94717656 -2.30237508 -0.34181426]
 [-2.30237508 10.94924131  2.86109993]
 [-0.34181426  2.86109993  3.08503464]]


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [104]:
# Conditional logic as array operations
my_array_6 = np.random.randn(4,4)
print(my_array_6)
np.where(my_array_6>0,2,my_array_6)

[[-0.23059937 -0.0635675   0.38043652 -0.70804744]
 [-0.80668308  0.77165994  0.62289927 -0.41444388]
 [ 0.31908457 -0.12373906  0.9209781   0.59659031]
 [ 0.29910253  0.74615159 -0.84480144  1.89189732]]


array([[-0.23059937, -0.0635675 ,  2.        , -0.70804744],
       [-0.80668308,  2.        ,  2.        , -0.41444388],
       [ 2.        , -0.12373906,  2.        ,  2.        ],
       [ 2.        ,  2.        , -0.84480144,  2.        ]])

In [105]:
# Mathematical and statistical methods
my_array_7 = np.random.rand(5,5)
for i in range(5):
    my_array_7[i]=i
print(my_array_7)
print('\n')
print(my_array_7.mean())

my_array_7.cumsum(0)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


2.0


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10.]])

In [106]:
# Linear algebra
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6],[11,21],[8,9]])
print (x, '\n\n', y)
print('\n')
print(x.dot(y))

from numpy.linalg import inv,qr
math = x.T.dot(x)
print('\n')
print(math)
print('\n')
r = qr(math)
print(r)

[[1 2 3]
 [4 5 6]] 

 [[ 5  6]
 [11 21]
 [ 8  9]]


[[ 51  75]
 [123 183]]


[[17 22 27]
 [22 29 36]
 [27 36 45]]


(array([[-0.43864578,  0.8005768 ,  0.40824829],
       [-0.56765924,  0.10533905, -0.81649658],
       [-0.69667271, -0.5898987 ,  0.40824829]]), array([[-3.87556448e+01, -5.11925427e+01, -6.36294407e+01],
       [ 0.00000000e+00, -5.68830885e-01, -1.13766177e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.55431223e-15]]))


In [107]:
# ------------------------Series------------------------------

#class pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
import pandas as pd
my_pandas_series = pd.Series(my_array)
my_pandas_series


0    1
1    2
2    3
dtype: int64

In [108]:
import pandas as pd
my_pandas_series = pd.Series(data = [3,2,4,6,10], index = ['a','b','c','d','e'])
print(my_pandas_series[:2])
print('\n')
print(my_pandas_series['b'])
print('\n')
print(my_pandas_series[my_pandas_series > 3])

a    3
b    2
dtype: int64


2


c     4
d     6
e    10
dtype: int64


In [109]:
# Create Pandas Series from a dict
state_pop = {'California':39500000, 'new york':19450000, 'new jersey':8800000}
s_state = pd.Series(state_pop)
print(s_state)
states = ['California','new york','new jersey','ohio']
s_state_reIndex = pd.Series(state_pop,index = states)
print('\n')

# Detect missing data
print(s_state_reIndex)
print(s_state_reIndex.isnull())
print('\n')

# Data alignment
ohio_CA_pop = {'ohio': 11600000,'California':39500000}
ohio_CA = pd.Series(ohio_CA_pop)
print(ohio_CA)
print(s_state_reIndex + ohio_CA)

# Ranking
s_state.rank(ascending=False,method='max')

California    39500000
new jersey     8800000
new york      19450000
dtype: int64


California    39500000.0
new york      19450000.0
new jersey     8800000.0
ohio                 NaN
dtype: float64
California    False
new york      False
new jersey    False
ohio           True
dtype: bool


California    39500000
ohio          11600000
dtype: int64
California    79000000.0
new jersey           NaN
new york             NaN
ohio                 NaN
dtype: float64


California    1.0
new jersey    3.0
new york      2.0
dtype: float64

In [110]:
# -----------------------Dataframe----------------------------------------

#A Dataframe is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns
data_dic = {'name':['joey','sam','nancy','monica'],
            'age': [33,29,25,31]}
my_df = pd.DataFrame (data_dic)
my_df.index.name='index';my_df.columns.name = 'Students'
print(my_df)
print('\n')

# 'values' returns the data contained in the Dataframe as a 2D array
print(my_df.values)

Students  age    name
index                
0          33    joey
1          29     sam
2          25   nancy
3          31  monica


[[33 'joey']
 [29 'sam']
 [25 'nancy']
 [31 'monica']]


In [111]:
# Indexing
print(my_df["name"][1])
print('\n')
print(my_df["name"][:-1])

# Reindexing
# Calling reindex may introduce missing values if any index values were not present
print(my_df)
my_df_2 = my_df.reindex([0,1,2,3,4])
print(my_df_2)

sam


index
0     joey
1      sam
2    nancy
Name: name, dtype: object
Students  age    name
index                
0          33    joey
1          29     sam
2          25   nancy
3          31  monica
Students   age    name
index                 
0         33.0    joey
1         29.0     sam
2         25.0   nancy
3         31.0  monica
4          NaN     NaN


In [112]:
# Sorting and ranking

my_df_3 = pd.DataFrame ({'c': [4,6,9,-1],'a':[0,0,1,1],'b': [3,6,-2,10]})
print(my_df_3.sort_index(by =['a','b']))
print('\n')
print(my_df_3.rank(axis=1))

   a   b  c
0  0   3  4
1  0   6  6
2  1  -2  9
3  1  10 -1


     a    b    c
0  1.0  2.0  3.0
1  1.0  2.5  2.5
2  2.0  1.0  3.0
3  2.0  3.0  1.0


/Users/sanduhr/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)


In [113]:
# Summarizing and computing descriptive statistics
print(my_df_3.sum())
print('\n')
print(my_df_3.mean())
print('\n')
print(my_df_3.idxmax())
print('\n')
print(my_df_3.describe())

a     2
b    17
c    18
dtype: int64


a    0.50
b    4.25
c    4.50
dtype: float64


a    2
b    3
c    2
dtype: int64


             a          b         c
count  4.00000   4.000000  4.000000
mean   0.50000   4.250000  4.500000
std    0.57735   5.057997  4.203173
min    0.00000  -2.000000 -1.000000
25%    0.00000   1.750000  2.750000
50%    0.50000   4.500000  5.000000
75%    1.00000   7.000000  6.750000
max    1.00000  10.000000  9.000000


In [122]:
# Filling in missing values

my_df_4 = pd.DataFrame ({'c': [4,6,9,-1],'a':[0,0,1,1],'b': [3,6,-2,10],'d':[0,0,0,0]})
my_df_4['d'] = np.NaN
print(my_df_4)
print('\n')
print(my_df_4.fillna(0))
print('\n')
print(my_df_4.fillna(data.mean()))
print('\n')
#print(my_df_4.fillna({'d':0.5})

   a   b  c   d
0  0   3  4 NaN
1  0   6  6 NaN
2  1  -2  9 NaN
3  1  10 -1 NaN


   a   b  c    d
0  0   3  4  0.0
1  0   6  6  0.0
2  1  -2  9  0.0
3  1  10 -1  0.0


   a   b  c         d
0  0   3  4 -0.390404
1  0   6  6 -0.390404
2  1  -2  9 -0.390404
3  1  10 -1 -0.390404


