In [2]:
#---------------------------------list---------------------------------------#

#list is a collection which is ordered and changeable. Allows duplicate members. Content can be modified.
#Two ways to define a list
my_list = ['Niu','Gu','Shi']

food = ['apples','beef','potatos','pasta']
my_list_2 = list (food)

# Combining lists
my_list_combined = my_list + my_list_2
my_list_combined.extend(['a','b','c'])

my_list_combined

['Niu', 'Gu', 'Shi', 'apples', 'beef', 'potatos', 'pasta', 'a', 'b', 'c']

In [3]:
# Adding/removing elements
my_list.append('Santa')

# Insert an element at a specific location
my_list.insert(1,'(1,2)')

print (my_list)

['Niu', '(1,2)', 'Gu', 'Shi', 'Santa']


In [4]:
# Remove an element at a particular index
my_list.pop(1)
my_list

# Element can also be removed by value
my_list.remove('Santa')
my_list

['Niu', 'Gu', 'Shi']

In [5]:
# Check if a list contains a value
'Gu' in my_list

True

In [6]:
# Sort a list 
list_a = [1,5,7,3,5,9,7,33,4,77,8,5,701,109]
list_a.sort()
list_a

# Sort strings by lengths
my_list.sort(key=len)
my_list


['Gu', 'Niu', 'Shi']

In [7]:
# Binary search & Maintain a sorted list
import bisect as bi

# Find the location to be inserted
bi.bisect(list_a,55)

# Find the location and insert a new element in a sorted list
bi.insort(list_a,888)

list_a

[1, 3, 4, 5, 5, 5, 7, 7, 8, 9, 33, 77, 109, 701, 888]

In [8]:
# Slicing 
print(my_list[1:2])
print(my_list[:1])
print(my_list[2:])
print(my_list[-2])
print(my_list[-2:])
print(my_list[::2])
print(my_list[::-2])
print(my_list[-2::])
print(my_list[-2:-1])


['Niu']
['Gu']
['Shi']
Niu
['Niu', 'Shi']
['Gu', 'Shi']
['Shi', 'Gu']
['Niu', 'Shi']
['Niu']


In [9]:
#---------------------------------tuple---------------------------------------#

# A tuple is a one-dimensional, fixed-length, immutable sequence of Python Objects

my_tup = 4,5,6
print(my_tup)

# Element can be accessed with []
print(my_tup[2])

# Unpacking tuples
a,b,c = my_tup
print(b)

my_tup2 = 7,8,(9,10)
a,b,(c,d) = my_tup2

(4, 5, 6)
6
5


In [10]:
# Any sequence can be converted to a tuple

print(tuple(['can','I','be','a','tuple','?']))

tuple_string = tuple('string')

('can', 'I', 'be', 'a', 'tuple', '?')


In [11]:
# tuple method

my_tup3 = ('a','e','f','c','g','b','c','d','e','a','a','a')
my_tup3.count('a')

4

In [12]:
#---------------------------------set---------------------------------------#

# A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets.
my_set = {'apples','bananas','carrots'}
print (my_set)

# Check if a set is a subset of another set
my_set_2 = {'apples'}

{'bananas', 'apples', 'carrots'}


In [13]:
# Mathematical set operations

set_a = {1,6,8,9,3}
set_b = {0,6,8,10,29,46,74,66}
print(set_a | set_b) #union
print(set_a ^ set_b)#symmetric difference
print(set_a & set_b) # and
print(set_a - set_b) # difference

{0, 1, 66, 3, 6, 8, 9, 10, 74, 46, 29}
{0, 1, 66, 3, 9, 10, 74, 29, 46}
{8, 6}
{1, 3, 9}


In [14]:
#---------------------------------dictionary---------------------------------------#

# A dictionary is a collection which is unordered, changeable and indexed. 
# In Python dictionaries are written with curly brackets, and they have keys and values.

thisdict = {
  "brand": "Nike",
  "model": "classic",
  "price": 198
}

print(thisdict.keys())
print(thisdict.values())

print(thisdict['model'])

# Check if a dict contains a key
print("brand" in thisdict)

# One dict can be merged into anothor dict
thisdict.update({'color': 'blk'})

dict_keys(['brand', 'model', 'price'])
dict_values(['Nike', 'classic', 198])
classic
True


In [15]:
 # Categorizing a list of color by it's first letter with a 'for loop'

colors = ['black','red','yellow','blue','grey','orange','green']
by_letter = {}
for color in colors:
    letter = color[0]
    if letter not in by_letter:
        by_letter[letter] = [color]
    else:
        by_letter[letter].append(color)
            
by_letter

{'b': ['black', 'blue'],
 'g': ['grey', 'green'],
 'o': ['orange'],
 'r': ['red'],
 'y': ['yellow']}

In [16]:
# List, set and dict comprehension allows you to form a new list by filtering the elements

#[expr for val in collection if condition]

the_city = ['yellow','taxi','New York']
print( [x.upper() for x in the_city if len(x)>7] )


lengths = {len(x) for x in the_city}
print(lengths)

mapping = {k : index for index, k in enumerate(the_city)}
print(mapping)

['NEW YORK']
{8, 4, 6}
{'yellow': 0, 'taxi': 1, 'New York': 2}


In [17]:
#Numpy array is a fast, flexible container for large data sets in Python.

import numpy as np
my_array = np.array([1, 2, 3])
my_array

#Multi-dimentional array
my_ndarray = np.array([[3,4,5],[6,7,8]])
print("my_ndarray = ",my_ndarray)
print("np.zeros = ",np.zeros((3,6)))

my_ndarray =  [[3 4 5]
 [6 7 8]]
np.zeros =  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
#Basic indexing and slicing
my_ndarray = np.array([[3,4,5],[6,7,8],[7,2,8],[6,6,6]])


print(my_ndarray[0][1])
print(my_ndarray[0,1])
print(my_ndarray[:1])
print(my_ndarray[:2,1:])
print(my_ndarray[:,:1])

4
4
[[3 4 5]]
[[4 5]
 [7 8]]
[[3]
 [6]
 [7]
 [6]]


In [19]:
# Boolean Indexing

names = np.array(['one','two','two','six','five','seven','two','one'])
data = np.random.randn(8,5)
print(names)
print(data)
print('\n')
print(names == 'one')
print(data[names == 'one'])
print('\n')
print(data[names == 'one', 3])


['one' 'two' 'two' 'six' 'five' 'seven' 'two' 'one']
[[-1.42541363 -0.74992025  2.000302    0.66950898  0.86506428]
 [ 1.32687567  0.32203969  1.08593956  1.65003947  0.63365086]
 [ 0.27654844  0.12270779 -1.91979805  0.34162652  1.36132855]
 [ 0.80263463 -0.69115579  1.90252134 -1.37954677  1.81653947]
 [ 0.07264898  0.82144606 -0.50386146 -0.45648058  1.26423587]
 [-0.76346101 -0.01893189  1.24192573  0.75978429  0.02701879]
 [ 1.26371508  0.15091135 -0.23897708  0.53073569 -0.07513877]
 [-0.44930281  1.3693586  -0.50366086  0.13172849 -0.67930703]]


[ True False False False False False False  True]
[[-1.42541363 -0.74992025  2.000302    0.66950898  0.86506428]
 [-0.44930281  1.3693586  -0.50366086  0.13172849 -0.67930703]]


[0.66950898 0.13172849]


In [20]:
# Fancy Indexing
my_array_2 = np.empty((7,5))
for i in range(7):
    my_array_2[i]=i
         
print(my_array_2)
print('\n')

# Select a subset of the rows in a particular order
print(my_array_2[[5,6,2,3]])
print('\n')
print(my_array_2[[-5,-6,-2,-3]])
print('\n')

# Reshape
my_array_3 = np.arange(16).reshape((2,8))
print(my_array_3)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]


[[5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5.]
 [4. 4. 4. 4. 4.]]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [37]:
# Inner matrix product
my_array_4 = np.random.randn(6,3)
print(my_array_4)
print(np.dot(my_array_4.T,my_array_4))
print('\n')

# Transposing
my_array_5 = np.arange(16).reshape(((2,2,4)))
print(my_array_5)
my_array_5.transpose((1,0,2))

[[ 0.18923233 -1.02335551  0.6577996 ]
 [-0.39907635  0.34950608 -1.13483097]
 [-0.99440155 -0.99325095  0.86102299]
 [-0.8939177  -1.03570296  0.06107991]
 [-0.55785332 -1.53601465 -1.22538365]
 [ 0.28379818  0.60924201 -1.11177591]]
[[ 2.37473585  2.61016459  0.03462251]
 [ 2.61016459  5.9591559  -0.78339906]
 [ 0.03462251 -0.78339906  5.20324373]]


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [41]:
# Conditional logic as array operations
my_array_6 = np.random.randn(4,4)
print(my_array_6)
np.where(my_array_6>0,2,my_array_6)

[[ 1.28844554e+00  6.70547126e-01 -7.78570711e-01 -7.41115279e-02]
 [-9.05586246e-01  1.37519502e-01  9.82722213e-04  8.84700763e-02]
 [ 2.44903195e-02  3.03942302e-01  1.02565987e+00  7.90524282e-01]
 [ 3.14764249e-02 -1.53772892e-01 -6.98316066e-01  9.52910340e-01]]


array([[ 2.        ,  2.        , -0.77857071, -0.07411153],
       [-0.90558625,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.15377289, -0.69831607,  2.        ]])

In [50]:
# Mathematical and statistical methods
my_array_7 = np.random.rand(5,5)
for i in range(5):
    my_array_7[i]=i
print(my_array_7)
print('\n')
print(my_array_7.mean())

my_array_7.cumsum(0)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


2.0


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.],
       [10., 10., 10., 10., 10.]])

In [67]:
# Linear algebra
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[5,6],[11,21],[8,9]])
print (x, '\n\n', y)
print('\n')
print(x.dot(y))

from numpy.linalg import inv,qr
math = x.T.dot(x)
print('\n')
print(math)
print('\n')
r = qr(math)
print(r)

[[1 2 3]
 [4 5 6]] 

 [[ 5  6]
 [11 21]
 [ 8  9]]


[[ 51  75]
 [123 183]]


[[17 22 27]
 [22 29 36]
 [27 36 45]]


(array([[-0.43864578,  0.8005768 ,  0.40824829],
       [-0.56765924,  0.10533905, -0.81649658],
       [-0.69667271, -0.5898987 ,  0.40824829]]), array([[-3.87556448e+01, -5.11925427e+01, -6.36294407e+01],
       [ 0.00000000e+00, -5.68830885e-01, -1.13766177e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.55431223e-15]]))


In [22]:
#class pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
import pandas as pd
my_pandas_series = pd.Series(my_array)
my_pandas_series


0    1
1    2
2    3
dtype: int64

In [23]:
import pandas as pd
my_pandas_series = pd.Series(data = ['3','2','4','6','10'], index = ['a','b','c','d','e'])
my_pandas_series[:2]

a    3
b    2
dtype: object

In [24]:
#A Dataframe is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns
data_dic = {'name':['joey','sam','nancy','monica'],
            'age': [33,29,25,31]}
my_df = pd.DataFrame (data_dic)
my_df["name"][1]

'sam'

In [25]:
#attribute value to a dataframe
data = {'a':['1']}
test = pd.DataFrame(data)
test['a'][0]
print(test)


   a
0  1
